## Find package: SuiteSparse
##
## SUITESPARSE_INCLUDE_DIR    include file directory
## SUITESPARSE_LIBRARY_DIR    library file directory
## SUITESPARSE_LIBRARIES      libraries
## SUITESPARSE_FOUND          found package?

if (SUITESPARSE_INCLUDE_DIR AND SUITESPARSE_LIBRARIES)
  set(SUITESPARSE_FIND_QUIETLY TRUE)
endif()

find_path(SUITESPARSE_INCLUDE_DIR
  NAMES
  umfpack.h cholmod.h
  PATHS
  $ENV{SUITESPARSE_INCLUDE_DIR}
  ${INCLUDE_INSTALL_DIR}
  PATH_SUFFIXES
  suitesparse
  )

find_library(SUITESPARSE_LIBRARIES umfpack PATHS $ENV{SUITESPARSE_LIBRARY_DIR} ${LIB_INSTALL_DIR})

if(SUITESPARSE_LIBRARIES AND SUITESPARSE_INCLUDE_DIR)

  get_filename_component(SUITESPARSE_LIBRARY_DIR ${SUITESPARSE_LIBRARIES} PATH)
  set(SUITESPARSE_FOUND TRUE)

else()

  set(SUITESPARSE_LIBRARIES)
  set(SUITESPARSE_INCLUDE_DIR)

endif()

if(SUITESPARSE_LIBRARIES)
  
  find_library(CHOLMOD_LIB cholmod PATHS ${SUITESPARSE_LIBRARY_DIR} $ENV{SUITESPARSE_LIBRARY_DIR} ${LIB_INSTALL_DIR})

  if(CHOLMOD_LIB) 
    set(SUITESPARSE_LIBRARIES ${SUITESPARSE_LIBRARIES} ${CHOLMOD_LIB})
  endif()

  find_library(CCOLAMD_LIB ccolamd PATHS ${SUITESPARSE_LIBRARY_DIR} $ENV{SUITESPARSE_LIBRARY_DIR} ${LIB_INSTALL_DIR})

  if(CCOLAMD_LIB) 
    set(SUITESPARSE_LIBRARIES ${SUITESPARSE_LIBRARIES} ${CCOLAMD_LIB})
  endif()

  find_library(COLAMD_LIB colamd PATHS ${SUITESPARSE_LIBRARY_DIR} $ENV{SUITESPARSE_LIBRARY_DIR} ${LIB_INSTALL_DIR})

  if(COLAMD_LIB) 
    set(SUITESPARSE_LIBRARIES ${SUITESPARSE_LIBRARIES} ${COLAMD_LIB})
  endif()

  find_library(CAMD_LIB camd PATHS ${SUITESPARSE_LIBRARY_DIR} $ENV{SUITESPARSE_LIBRARY_DIR} ${LIB_INSTALL_DIR})

  if(CAMD_LIB) 
    set(SUITESPARSE_LIBRARIES ${SUITESPARSE_LIBRARIES} ${CAMD_LIB})
  endif()

  find_library(AMD_LIB amd PATHS ${SUITESPARSE_LIBRARY_DIR} $ENV{SUITESPARSE_LIBRARY_DIR} ${LIB_INSTALL_DIR})

  if(AMD_LIB) 
    set(SUITESPARSE_LIBRARIES ${SUITESPARSE_LIBRARIES} ${AMD_LIB})
  endif()

  find_library(METIS_LIB metis PATHS ${SUITESPARSE_LIBRARY_DIR} $ENV{SUITESPARSE_LIBRARY_DIR} ${LIB_INSTALL_DIR})
  
  if(METIS_LIB) 
    set(SUITESPARSE_LIBRARIES ${SUITESPARSE_LIBRARIES} ${METIS_LIB})
  endif()

endif()

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(SUITESPARSE DEFAULT_MSG
                                  SUITESPARSE_INCLUDE_DIR SUITESPARSE_LIBRARIES)

mark_as_advanced(SUITESPARSE_INCLUDE_DIR SUITESPARSE_LIBRARIES)
