
# set(PROJECT )
# set(PROJECT_LANGUAGES CXX C Fortran)

#### set project version

set(PROJECT_MAJOR_VERSION 0) 
set(PROJECT_MINOR_VERSION 0)
set(PROJECT_PATCH_VERSION 1)

set(PROJECT_COPYRIGHT "(C) 2012" )